### ISSUE TITLE
Can't handle certain characters

### ISSUE THREAD

**Issue by YoungSensei-TSU** [tylerneylon/explacy#3]
Have a document where a colon (:) is followed by a space ( ) and receive an error every time.

  File "redacted", line 182, in <listcomp>
    for ch in lines[i]]
KeyError: 'ens'

**Comment by ldorigo** [comment]
Same issue.

**Comment by tylerneylon** [comment]
Any chance I can see a small reproducible example? That would be helpful for debugging. Thanks!

**Comment by ankur-gupta** [comment]
I think I have a similar issue. Here are some examples. 

```
explacy.print_parse_info(nlp, "I hate cats; I love dogs.")  # Fails
explacy.print_parse_info(nlp, "I hate cats but I love dogs.")  # Fails
explacy.print_parse_info(nlp, "I hate cats")  # Fails
explacy.print_parse_info(nlp, "I hate cats.")  # Passes
```

The error looks like this for me:
```
explacy.print_parse_info(nlp, "I hate cats")  # Fails
Traceback (most recent call last):
  File "/Users/<redacted-path>/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-101-92ef89041528>", line 1, in <module>
    explacy.print_parse_info(nlp, "I hate cats")  # Fails
  File "/Users/<redacted-path>/explacy.py", line 182, in print_parse_info
    for ch in lines[i]]
  File "/Users/<redacted-path>/explacy.py", line 182, in <listcomp>
    for ch in lines[i]]
KeyError: 'ens'
```

In the code, I see no key for `ens`:
```
# Lines 170-176 as of Dec 31, 2019 code
    arr_chars = {'ew'  : u'─',
                 'ns'  : u'│',
                 'en'  : u'└',
                 'es'  : u'┌',
                 'enw' : u'┴',
                 'ensw': u'┼',
                 'esw' : u'┬'}
```
Can we add a symbol for the `ens` sequence or is `ens` an impossible sequence?

**Comment by basiliskAI** [comment]
Don't know if you've all already solved this, but in case anyone else hits this roadblock: there's a fork at https://github.com/bionandojr/explacy that includes this line:
`                 'ens' : u'├',`
in that same dictionary. Worked for me!

**Comment by tylerneylon** [comment]
Sorry I was slow to fix this. I accepted #1 that I believe fixes this!
