### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by iliakur** [tylerneylon/explacy#5]
What's the license of this code?

I was thinking of using this at work but turning it into a python package and uploading it to our internal pypi repository. If you're interested, I could also open a PR with the packaging setup once I've got it working.

**Comment by tylerneylon** [comment]
Please consider this public domain. Sure, I’d be happy to see the packaging
setup!

Thanks!
 - Tyler

**Comment by iliakur** [comment]
Hi @tylerneylon, thanks for your response.

Just fyi, according to the Open Source Initiative [public domain is not the same as open source](https://opensource.org/node/878).

You may want to slap on a permissive license just in case. Something like BSD or MIT should be hassle-free.

**Comment by tylerneylon** [comment]
I added the `UNLICENSE` file to help solidify the permission of others to do what they would like with this project.
